# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foobar.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='foobar.proto',
  package='foobar_grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x66oobar.proto\x12\x0b\x66oobar_grpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n\x06\x46oobar\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x15\n\rFoobarContent\x18\x02 \x01(\t\x12-\n\tUpdatedAt\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tCreatedAt\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"2\n\nListFoobar\x12$\n\x07\x46oobars\x18\x01 \x03(\x0b\x32\x13.foobar_grpc.Foobar\".\n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x04\"\x1b\n\x0c\x46\x65tchRequest\x12\x0b\n\x03num\x18\x01 \x01(\x04\"\x1b\n\rSingleRequest\x12\n\n\x02ID\x18\x01 \x01(\t\"\x1f\n\x0c\x45rrorMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc2\x02\n\rFoobarHandler\x12<\n\tGetFoobar\x12\x1a.foobar_grpc.SingleRequest\x1a\x13.foobar_grpc.Foobar\x12\x43\n\rGetListFoobar\x12\x19.foobar_grpc.FetchRequest\x1a\x17.foobar_grpc.ListFoobar\x12\x38\n\x0cUpdateFoobar\x12\x13.foobar_grpc.Foobar\x1a\x13.foobar_grpc.Foobar\x12\x41\n\x06\x44\x65lete\x12\x1a.foobar_grpc.SingleRequest\x1a\x1b.foobar_grpc.DeleteResponse\x12\x31\n\x05Store\x12\x13.foobar_grpc.Foobar\x1a\x13.foobar_grpc.Foobarb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_FOOBAR = _descriptor.Descriptor(
  name='Foobar',
  full_name='foobar_grpc.Foobar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='foobar_grpc.Foobar.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FoobarContent', full_name='foobar_grpc.Foobar.FoobarContent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UpdatedAt', full_name='foobar_grpc.Foobar.UpdatedAt', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CreatedAt', full_name='foobar_grpc.Foobar.CreatedAt', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=200,
)


_LISTFOOBAR = _descriptor.Descriptor(
  name='ListFoobar',
  full_name='foobar_grpc.ListFoobar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Foobars', full_name='foobar_grpc.ListFoobar.Foobars', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=252,
)


_DELETERESPONSE = _descriptor.Descriptor(
  name='DeleteResponse',
  full_name='foobar_grpc.DeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='foobar_grpc.DeleteResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='foobar_grpc.DeleteResponse.code', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=300,
)


_FETCHREQUEST = _descriptor.Descriptor(
  name='FetchRequest',
  full_name='foobar_grpc.FetchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='foobar_grpc.FetchRequest.num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=329,
)


_SINGLEREQUEST = _descriptor.Descriptor(
  name='SingleRequest',
  full_name='foobar_grpc.SingleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='foobar_grpc.SingleRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=358,
)


_ERRORMESSAGE = _descriptor.Descriptor(
  name='ErrorMessage',
  full_name='foobar_grpc.ErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='foobar_grpc.ErrorMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=391,
)

_FOOBAR.fields_by_name['UpdatedAt'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FOOBAR.fields_by_name['CreatedAt'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LISTFOOBAR.fields_by_name['Foobars'].message_type = _FOOBAR
DESCRIPTOR.message_types_by_name['Foobar'] = _FOOBAR
DESCRIPTOR.message_types_by_name['ListFoobar'] = _LISTFOOBAR
DESCRIPTOR.message_types_by_name['DeleteResponse'] = _DELETERESPONSE
DESCRIPTOR.message_types_by_name['FetchRequest'] = _FETCHREQUEST
DESCRIPTOR.message_types_by_name['SingleRequest'] = _SINGLEREQUEST
DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Foobar = _reflection.GeneratedProtocolMessageType('Foobar', (_message.Message,), {
  'DESCRIPTOR' : _FOOBAR,
  '__module__' : 'foobar_pb2'
  # @@protoc_insertion_point(class_scope:foobar_grpc.Foobar)
  })
_sym_db.RegisterMessage(Foobar)

ListFoobar = _reflection.GeneratedProtocolMessageType('ListFoobar', (_message.Message,), {
  'DESCRIPTOR' : _LISTFOOBAR,
  '__module__' : 'foobar_pb2'
  # @@protoc_insertion_point(class_scope:foobar_grpc.ListFoobar)
  })
_sym_db.RegisterMessage(ListFoobar)

DeleteResponse = _reflection.GeneratedProtocolMessageType('DeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETERESPONSE,
  '__module__' : 'foobar_pb2'
  # @@protoc_insertion_point(class_scope:foobar_grpc.DeleteResponse)
  })
_sym_db.RegisterMessage(DeleteResponse)

FetchRequest = _reflection.GeneratedProtocolMessageType('FetchRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHREQUEST,
  '__module__' : 'foobar_pb2'
  # @@protoc_insertion_point(class_scope:foobar_grpc.FetchRequest)
  })
_sym_db.RegisterMessage(FetchRequest)

SingleRequest = _reflection.GeneratedProtocolMessageType('SingleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEREQUEST,
  '__module__' : 'foobar_pb2'
  # @@protoc_insertion_point(class_scope:foobar_grpc.SingleRequest)
  })
_sym_db.RegisterMessage(SingleRequest)

ErrorMessage = _reflection.GeneratedProtocolMessageType('ErrorMessage', (_message.Message,), {
  'DESCRIPTOR' : _ERRORMESSAGE,
  '__module__' : 'foobar_pb2'
  # @@protoc_insertion_point(class_scope:foobar_grpc.ErrorMessage)
  })
_sym_db.RegisterMessage(ErrorMessage)



_FOOBARHANDLER = _descriptor.ServiceDescriptor(
  name='FoobarHandler',
  full_name='foobar_grpc.FoobarHandler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=394,
  serialized_end=716,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFoobar',
    full_name='foobar_grpc.FoobarHandler.GetFoobar',
    index=0,
    containing_service=None,
    input_type=_SINGLEREQUEST,
    output_type=_FOOBAR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetListFoobar',
    full_name='foobar_grpc.FoobarHandler.GetListFoobar',
    index=1,
    containing_service=None,
    input_type=_FETCHREQUEST,
    output_type=_LISTFOOBAR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateFoobar',
    full_name='foobar_grpc.FoobarHandler.UpdateFoobar',
    index=2,
    containing_service=None,
    input_type=_FOOBAR,
    output_type=_FOOBAR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='foobar_grpc.FoobarHandler.Delete',
    index=3,
    containing_service=None,
    input_type=_SINGLEREQUEST,
    output_type=_DELETERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Store',
    full_name='foobar_grpc.FoobarHandler.Store',
    index=4,
    containing_service=None,
    input_type=_FOOBAR,
    output_type=_FOOBAR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOOBARHANDLER)

DESCRIPTOR.services_by_name['FoobarHandler'] = _FOOBARHANDLER

# @@protoc_insertion_point(module_scope)
